export const currencies: Currency[] = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "AED", name: "United Arab Emirates Dirham" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "IRR", name: "Iranian Rial" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "OMR", name: "Omani Rial" },
  { code: "QAR", name: "Qatari Rial" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "YER", name: "Yemeni Rial" },
];
